## Обработка ошибок

```js
// Создаем Subject
const subject = new Subject();

// Создаем подписчиков на Subject
const subscriber_1$ = subject.subscribe(
  (x: number) => console.log('Подписка 1:', x), // обработчик next
  (error) => console.log('Подписка 1 ошибка:', error), // обработчик error
  () => console.log('Подписка 1: stream completed') // обработчик complete
);

const subscriber_2$ = subject.subscribe(
  (x: number) => console.log('Подписка 2:', x * 10),
  (error) => console.log('Подписка 2 ошибка:', error),
  () => console.log('Подписка 2: stream completed')
);

// Пушим данные в Subject - все подписчики получат эти данные внутри обработчика next
subject.next(1);

// Если у Subject вызвать метод error() - все подписчики смогут обработать вызванную ошибку
// внутри обработчика error
subject.error(new Error('Err msg...'));

// Пушим данные в Subject после возникновения ошибки -
// данные будут утеряны
subject.next(2);

// РЕЗУЛЬТАТ:
// Подписка 1: 1
// Подписка 2: 10
// Подписка 1 ошибка: Error: Err msg...
// Подписка 2 ошибка: Error: Err msg...
```